// gen_schema_js.js — generate vendor/project_meta_schema.js, a <script>-loadable
// UMD wrapper of the canonical schema, from docs/schemas/project_meta.schema.json.
//
// Why: the webapp runs under file:// where fetch()/XHR of local JSON is blocked
// (same constraint that forces the fonts to be JS-wrapped — see index.html). So
// ProjectMeta.setSchema() can't read the .json at runtime; the schema is embedded
// as a JS module instead.
//
// Regenerate after editing the canonical schema:
//   node tools/gen_schema_js.js
//
// Drift: tools/check_schema_drift.js compares the embedded copy's parsed object
// against the canonical so a stale wrapper is caught in CI/merge-gate.

var fs = require("fs");
var path = require("path");

var ROOT = path.resolve(__dirname, "..");
var SRC = path.join(ROOT, "docs", "schemas", "project_meta.schema.json");
var DEST = path.join(ROOT, "vendor", "project_meta_schema.js");

var raw = fs.readFileSync(SRC, "utf8");
var obj = JSON.parse(raw); // assert it parses; throws loudly if canonical is broken
var pretty = JSON.stringify(obj, null, 4);

var out =
    "// project_meta_schema.js — GENERATED by tools/gen_schema_js.js. DO NOT EDIT BY HAND.\n" +
    "// Source of truth: docs/schemas/project_meta.schema.json\n" +
    "// Regenerate: node tools/gen_schema_js.js   (drift-checked by tools/check_schema_drift.js)\n" +
    "// Reason: webapp runs under file://; fetch() of local JSON is blocked, so the\n" +
    "// canonical schema is embedded here as a <script>-loadable UMD module.\n" +
    "(function (root, factory) {\n" +
    "    if (typeof module === \"object\" && module.exports) module.exports = factory();\n" +
    "    else root.ProjectMetaSchema = factory();\n" +
    "}(typeof self !== \"undefined\" ? self : this, function () {\n" +
    "    \"use strict\";\n" +
    "    return " + pretty.split("\n").join("\n    ") + ";\n" +
    "}));\n";

fs.writeFileSync(DEST, out, "utf8");
console.log("Wrote " + DEST + " (" + Buffer.byteLength(out, "utf8") + " bytes) from " + path.relative(ROOT, SRC));
